[project]
name = "risk-calculation-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastmcp>=2.9.0",
    "langchain-google-genai>=2.1.5",
    "langgraph>=0.4.9",
    "yfinance>=0.2.63",
]
